# This file was generated by GoReleaser. DO NOT EDIT.
cask "walletspace" do
  define_singleton_method(:walletspace_postflight_steps) do
    postflight_steps do
      on_macos do
        run "/usr/bin/xattr",
            args: ["-d", "-r", "com.apple.quarantine", "{{staged_path}}/walletspace"]
      end
    end
  end

  walletspace_postflight_steps

  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "09a4ee88a8eff18339719168075e2e8c4bee2798e60389c0fa5da79fc300f5de"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a62aa1d0874ff7307816b5ef54d7ade17e3d576772e1fd0dee262d0a7a5402d9"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "352217cf55f1c7b7d16e1a157ae361d9c94e748413675597b5d916deec994350"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33576c99a2c8c62d133f220a03343d64b64282a86fd6cd5cbb73a713f653f43f"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "walletspace"
  desc "Local multichain wallet manager with encrypted vaults and a loopback UI"
  homepage "https://github.com/sxwebdev/walletspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "walletspace"

  # No zap stanza required

  caveats <<~EOS
    Wallet data stays in ~/.walletspace and is left in place when the cask is
    removed. Back up every recovery phrase before deleting that directory:
    nothing else can restore the wallets.

    Start the UI with `walletspace`; it listens on loopback only.
  EOS
end
