# This file was generated by GoReleaser. DO NOT EDIT.
cask "walletspace" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5e6f296b1d7594f14e1302c9dba50ceb3e1857825b7c26947528a7886285d36f"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89840cafe46bc8b6ad1de1898103cc1dd1a819943a7e0706212cc08ec4d18f13"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "285c05e16dcd6d20f629e919cdced6436b3ec154a0a7fc4d779755c2e8ddfc17"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcf5564dee96bbad5332333e3030e251568fa994cff57838a7bf2ff34e31310b"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "walletspace"
  desc "Local multichain wallet manager with encrypted vaults and a loopback UI"
  homepage "https://github.com/sxwebdev/walletspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "walletspace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/walletspace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wallet data stays in ~/.walletspace and is left in place when the cask is
    removed. Back up every recovery phrase before deleting that directory:
    nothing else can restore the wallets.

    Start the UI with `walletspace`; it listens on loopback only.
  EOS
end
