# This file was generated by GoReleaser. DO NOT EDIT.
cask "walletspace" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "c8f46c001e01c4f4d69a9bacfc5bd0fa2845aa8dde964e3fdac57e91a50e4b89"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94fa742e3b6b93c5000545934f98722ca2c7263e2e9256c986e228282469356b"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0cf8e6ea02637cb0595e0f9f381e56334860a8b88893fa242b9102fc595a4021"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "17e6e1c046cbeb37890cfbdaa4480e82868648ba63b42c615694c4f11233e23d"
      url "https://github.com/sxwebdev/walletspace/releases/download/v#{version}/walletspace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "walletspace"
  desc "Local multichain wallet manager with encrypted vaults and a loopback UI"
  homepage "https://github.com/sxwebdev/walletspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "walletspace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/walletspace"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wallet data stays in ~/.walletspace and is left in place when the cask is
    removed. Back up every recovery phrase before deleting that directory:
    nothing else can restore the wallets.

    Start the UI with `walletspace`; it listens on loopback only.
  EOS
end
